Create api information
LT-Students/DigitalOffice-TimeService pull request #16
Opened 2021-04-13 07:48 UTC by BelehovEgor

http://outsourcing.nat.tepkom.ru:20080/redmine/issues/283

2021-04-13 09:10 UTC, djino97 approved these changes

2021-04-13 10:07 UTC, KostinP requested changes
Add to skipped endpoints

2021-04-13 10:52 UTC, KostinP approved these changes

2021-04-13 12:01 UTC, TIove approved these changes

2021-04-14 11:00 UTC, borovHokage approved these changes

2021-04-14 11:11 UTC, merged